### ISSUE TITLE
Not possible to create some of the loan fixtures

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#838]
**Describe the issue**

During the execution of the script `scripts/setup` , you receive the following errors:
```
Errors active: 5
Errors requests: 11
Errors overdue: 1
Errors extended: 1
Errors requested_by_others: 2
Errors rank_1: 1
Errors rank_2: 1
```

**To Reproduce**
1. Checkout to the `rero_ils.dev` branch version 0.6.1
1. run `scripts/setup`
1. The errors above will show during the execution of the loan fixtures creation

**Traceback**
Seems to be related to `MEF` and the resource `person`
```
Traceback (most recent call last):
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/loans/cli.py", line 271, in create_request
    document_pid=item.replace_refs()['document']['pid'],
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/items/api.py", line 204, in wrapper
    item.status_update(dbcommit=True, reindex=True, forceindex=True)
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/items/api.py", line 698, in status_update
    self.dbcommit(reindex=True, forceindex=True)
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/api.py", line 389, in dbcommit
    self.reindex(forceindex=forceindex)
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/api.py", line 394, in reindex
    self.indexer(version_type="external_gte").index(self)
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/items/api.py", line 82, in index
    document.reindex()
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/api.py", line 396, in reindex
    self.indexer().index(self)
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/documents/api.py", line 55, in index
    record.index_persons()
  File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/documents/api.py", line 181, in index_persons
    person.reindex()
AttributeError: 'NoneType' object has no attribute 'reindex'
```

**Comment by rerowep** [comment]
Problem solved on MEF.
